export default {
  // The class name
  name: {
    en: 'Warrior',
    el: 'Πολεμιστής',
    de: 'Krieger',
    ru: 'Воин',
    bg: 'Воин',
    es: 'Guerrero',
    fr: 'Guerrier',
    hi: 'योधा',
    ko: '전사',
    pt: 'Guerreiro',
    tr: 'Savaşçı',
    nl: 'Krijger',
    ro: 'Războinic',
    zh: '戰士',
    hu: 'Harcos',
    pl: 'Wojownik',
    bn: 'যোদ্ধা',
    vi: 'Chiến binh',
    cs: 'Válečník',
    sr: 'Ратник',
    it: 'Guerriero',
    id: 'Pejuang'
  },
  // Class description, visible during character creation
  description: {
    en: 'Warriors are built to tank more monsters than any other class by having high defense through equipment (Shields) and strong defensive buffs.',
    el: 'Οι πολεμιστές μπορούν να έχουν τον ρόλο του Tank επειδή έχουν υψηλή άμυνα μέσω του εξοπλισμού τους (Ασπίδες) και δυνατά αμυντικά ξόρκια.',
    ru: 'Воины созданы для того, чтобы танковать больше монстров чем любой другой класс, имея хорошую защиту с помощью снаряжения (Щита) и сильных защитных усилений.',
    de: 'Krieger sind so gebaut, dass sie mehrere Monster auf einmal aushalten können, da sie eine hohe Verteidigung durch Ausrüstung (Schilde) und starke defensive Buffs haben.',
    es: 'Los guerreros están hechos para resistir más daño de los monstruos que cualquier otra clase mediante su gran defensa, su equipamiento (escudos) y sus fuertes Buffs(ventajas) defensivos.',
    fr: 'Les guerriers sont conçus pour encaisser plus de monstres que n\'importe quelle autre classe en ayant une défense élevée grâce à leurs équipements (Boucliers) et des buffs défensifs puissants.',
    hi: 'सर्वश्रेष्ठ रक्षा उपकरण और ताक़तवर कवच के उपयोग से सारी श्रेणियो में योधा सबसे अधिक मार रोक सकते हैं।',
    ko: '전사들은 장비 (방패)와 강력한 방어 숙련자를 통해 높은 방어력을 가짐으로써 다른 클래스보다 더 많은 몬스터를 견딜수 있습니다.',
    pt: 'Os guerreiros são feitos de forma a resistir a mais monstros do que qualquer outra classe, tendo alta defesa através de equipamentos (Escudos) e fortes buffs defensivos.',
    nl: 'Krijgers zijn bedoeld om meer schade op te vangen dan enig andere klasse via middel van bepaalde verdedigingsuitrusting (Schilden) en sterke defensieve betoveringen.',
    tr: 'Savaşçılar güçlü defansif ekipmanları (Kalkanlar) ve defansif güçlendirmeleri ile canavarları diğer sınıflardan daha çok üstüne çeker.',
    ro: 'Războinicii sunt făcuți pentru a atrage mai mulți monștrii decât orice altă clasă, având o defensivă foarte ridicată datorită echipamentului (Scuturi) și buff-uri defensive puternice.',
    zh: '通過裝備（盾牌）和強大的防守增益效果，戰士可以打敗比其他角色更多的怪物。',
    hu: 'A harcosok hatalmas védekező képességükre és erejükre támaszkodva magukra vállalhatják a közelharcot számos ellenséggel, hogy a csapatjuk többi tagja zavartalanul használhassa mágiáját.',
    pl: 'Wojownicy są stworzeni aby tankować więcej potworów niż jakakolwiek inna klasa, a to dzięki wysokiej obronie i pomocy wyposażenia (tarcze) oraz silnych buffów obronnych.',
    bn: 'যোদ্ধারা অন্য যেকোনো শ্রেণী থেকে বেশী শত্রু যখম করতে পারে তাদের সরঞ্জামের (ঢাল) ও শক্তিশালী বাফের থেকে পাওয়া উচ্চমাত্রার প্রতিরক্ষা ব্যাবস্থার ফলে।',
    vi: 'Chiến binh được xây dựng để chống chịu trước nhiều quái vật hơn các lớp nhân vật khác bởi vì có sức phòng thủ cao thông qua các trang bị (Khiên) và các buff phòng thủ mạnh mẽ.',
    cs: 'Válečníci jsou stavěni aby odolali více příšerám než ostatní povolání. Mají velice velkou obranu zkrze štít a obranné buffy.',
    sr: 'Ослањајући се на своју огромну одбрану и снагу, ратници се могу укључити у борбу против бројних непријатеља, тако да остали чланово његовог тима могу неометано користити магију.',
    it: 'I Guerrieri sono creati per tankare più mostri rispetto alle altri classi avendo una difesa alta grazie a scudi e forti buff difensivi.',
    id: 'Pejuang dilatih untuk menahan lebih banyak monster daripada kelas lain dengan memunyai pertahanan tinggi dari peralatan (perisai) dan 𝑏𝑢𝑓𝑓 pertahanan kuat.'
  }
}
